apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ruby-cloud-git
  name: ruby-cloud-git
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ruby-cloud-git
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ruby-cloud-git
    spec:
      containers:
        - env:
            - name: SECRET_KEY_BASE
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY_BASE
                  name: ruby-cloud-git-config-gsnu
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: ruby-cloud-git-config-gsnu
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DB_USERNAME
                  name: ruby-cloud-git-config-gsnu
          image: gcr.io/people-283523/github.com/sebacav/cloud-to-git-cicd
          imagePullPolicy: IfNotPresent
          name: cloud-to-git-cicd-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: ruby-cloud-git
  name: ruby-cloud-git-hpa-53vf
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ruby-cloud-git
