apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gke-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
      - env:
        - name: CUSTOM_ENV_VARIABLE
          value: Value defined by Kustomize
        image: gke-test
        name: app
        ports:
        - containerPort: 80
          name: http
          protocol: TCP