apiVersion: v1
kind: Service
metadata:
  name: gitcicd
  namespace: default
  labels:
    app: test-git-app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: test-git-app
  type: LoadBalancer