apiVersion: v1
metadata:
  name: test-service
spec:
  selector:
    matchLabels:
      run: test-git-app
  replicas: 3
  service:
    ports:
    - name: http-function-port
      port: 8080
      protocol: TCP
      targetPort: 3000
    selector:
        app: test-git-app
  sessionAffinity: None
  type: LoadBalancer