apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  replicas: 3
  service:
    ports:
    - name: http-function-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
        app: test-git-app
  sessionAffinity: None
  type: LoadBalancer